### ISSUE TITLE
Graphemes to phonemes

### ISSUE THREAD

**Issue by huypl53** [NTT123/vietTTS#6]
I saw that your synthesized audio clip is good!
But the phoneme is just a single "character" like "ô ư i u ...", how about complicated cases (maybe better as I think) such as: hươu -> h ươu, thái -> th ái
I am trying FastSpeech2, but it seems not good. Did you hear it?
It is great if we can contact further. 
Thanks!

**Comment by NTT123** [comment]
@phamlehuy53, yes I agree that *real* phonemes instead of graphemes will be better. Though, it will require a bigger (and 
carefully designed) dataset to cover all vietnamese phonemes.

I haven't tried FastSpeech2. However, I think FastSpeech is not the problem, the training dataset is. The original InfoRe dataset is quite bad. I did use a speech enhancement network to improve it (denoised, etc.) Besides, training the network longer also helps to improve the speech quality.
